version: '3'

services:
  db:
    container_name: ks_db
    image: postgres:9.6.21-alpine
    restart: always
    volumes:
      - kariseediq-volume:/var/lib/postgresql/data
    env_file:
      - ./web/web-variables.env
  web:
    container_name: ks_web
    build: .
    volumes:
      - ./:/app/
    restart: always
    environment:
      - DOCKER=1
      - PYTHONUNBUFFERED=0
    ports:
      - "8002:8000"
    tty: true
    stdin_open: true
    depends_on:
      - db
  memcached:
    container_name: ks_memcached
    image: memcached:1.6.9
    entrypoint:
      - memcached
      - -m 64
volumes:
  kariseediq-volume:
