version: '3'

services:
  web:
    volumes:
      - ./web/:/app/web/
    command: >
      bash -c "python manage.py makemigrations --noinput
      && python manage.py migrate --noinput
      && python manage.py collectstatic --noinput
      && python -u manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=web.settings.local
      - DJANGO_LOG_LEVEL=DEBUG