version: '3'

services:
  db:
    image: postgres
    volumes:
      - kariseediq-volume:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - ./:/app/
    restart: always
    environment:
      - DOCKER=1
    ports:
      - "8002:8000"
    tty: true
    stdin_open: true
    depends_on:
      - db
volumes:
  kariseediq-volume:
