version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - ./:/app/
    restart: always
    ports:
      - "8002:8000"
    tty: true
    stdin_open: true
    depends_on:
      - db
