# Generated by Django 2.1.3 on 2018-11-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181126_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='wordClass',
            field=models.CharField(blank=True, choices=[('NOUN', '名詞'), ('VERB', '動詞'), ('MULTI', '多重詞性'), ('OTHER', '其他')], default='NOUN', max_length=255),
        ),
    ]
